apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 30080
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx